import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-white">
           <div className="flex items-center justify-between py-7 px-14 bg-cyan-900 text-white">
            <h1 className="text-3xl font-bold">Mini LMS</h1>
               <nav className="flex gap-6 text-lg">
                  <Link href="/courses">Courses</Link>
                  <Link href="/assessment">Assessment</Link>
                   <Link href="/dashboard">Dashboard</Link>
               </nav>
         </div>
        {children}</body>
    </html>
  );
}
